### ISSUE TITLE
The Guild is no longer in the repo

### ISSUE THREAD

**Issue by yannack** [queeup-archives/repository.queeup#1]
Hello,
The plugin for The Guild is not available in the repo. Living outside the US, using Hulu is not an option for me. Do you think you will consider adding the Guild plugin back to your repo? This would really be a lifesaver :)
Thanks
Yannack

**Comment by queeup** [comment]
Sure. But i will be back to my house 2 weeks later. Till then you have to wait :)

yannack notifications@github.com şunu yazdı:

**Comment by yannack** [comment]
Great news, thanks a lot! :)

**Comment by queeup** [comment]
Version 2.0.0 available on repo now.

**Comment by yannack** [comment]
great i'll give it a try ASAP :)
Thanks a lot!!
