### ISSUE TITLE
Democracy Now!

### ISSUE THREAD

**Issue by DanielBaulig** [queeup-archives/repository.queeup#4]
Hey, I was looking for a Democracy Now addon for XBMC. Apparently your repository once included an Democracy Now! addon. Either it was removed or I am too stupid to install it. If I'm too stupid could you explain how I can install it and if you removed it, do you know any other way to get hold of it?

**Comment by queeup** [comment]
Sorry it's my fault. I didn't commit all my add-ons to frodo repo :) You can find it and download trough XBMC now.
859ce06148

**Comment by DanielBaulig** [comment]
Cool, thanks!
